import { Paths } from 'types/paths';

export const paths: Paths = Object.freeze({
  auth: {
    signIn: '/auth/sign-in',
    createPassword: '/auth/create-password/:activationLink',
    invalidActivation: '/auth/invalid-activation',
    invalidPswResetData: '/auth/invalid-psw-reset-data',
  },
  home: '/',
  admin: {
    dashboard: '/admin',
    users: '/admin/users',
    addStudents: '/admin/users/add-students',
    groups: '/admin/groups',
    courses: '/admin/courses',
    teachers: '/admin/teachers',
    settings: '/admin/settings',
    account: '/admin/account',
  },
  teacher: {
    dashboard: '/teacher',
    groups: '/teacher/groups',
    groupDetails: '/teacher/groups/:id',
    courses: '/teacher/courses',
    courseCreate: '/teacher/courses/create',
    courseEdit: '/teacher/courses/:id',
    tasks: '/teacher/tasks',
    tasksCheck: '/teacher/tasks/:taskId',
    tests: '/teacher/tests',
    testsEdit: '/teacher/tests/:testId/edit',
    testsView: '/teacher/tests/:testId',
    settings: '/teacher/settings',
    account: '/teacher/account',
  },
  student: {
    dashboard: '/student',
    courses: '/student/courses',
    lessons: '/student/courses/:courseId',
    lesson: '/student/courses/:courseId/:lessonId',
    tasks: '/student/tasks',
    task: '/student/tasks/:taskId',
    tests: '/student/tests',
    testsView: '/student/tasks/:taskId/test',
    grades: '/student/grades',
    settings: '/student/settings',
    account: '/student/account',
  },
});
